GET http://localhost:3002/private/languages?token=yourtoken

###
GET http://localhost:3002/project/60491be244cafb58b49a779f

GET http://localhost:5000/api/rooms/5fa025e6a1da8a6194838d5f

###

PATCH http://localhost:3002/project/60491be244cafb58b49a779f HTTP/1.1
content-type: application/json

 {
        "links": [
            {"name": "code",
            "url": "test"
            }
        ],
        "devices": ["desktop"],
        "language": [
            "klk"
        ],
        "tags": [
            "lalala"
        ],
        "isMainProject": true,
        "name": "TETE DE KICHEtte",
        "description": "gaetano de la vega   ",
        "images": [
            {
                "_id": "60492033a51498342c972d8c",
                "name": "String",
                "url": "String"
            },
             {
                "_id": "60492033a51498342c972d8c",
                "name": "String",
                "url": "String"
            }
        ],
         "imageHome": 
            {
                "_id": "60492033a51498342c972d8c",
                "name": "String",
                "url": "String"
            }
    }
####

POST http://localhost:3002/signup HTTP/1.1
content-type: application/json

{
"email": "tst@tst.com",
"password": "test2mdpAsse",
"isAdmin": true
}
#####
POST http://localhost:3002/login HTTP/1.1
content-type: application/json

{
"email": "testgaeta@tst.com",
"password": "test",
}
##########
GET http://localhost:3002/private/secret?token=yourtoken HTTP/1.1
content-type: application/json

####
